# Generated by Django 5.0.6 on 2024-05-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Especie',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='tipo',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='nombre',
            new_name='numero_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='veterinario',
            field=models.ManyToManyField(to='tienda.veterinario'),
        ),
    ]
