# Generated by Django 5.0.6 on 2024-05-14 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_veterinario_rename_tipo_especie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edad',
        ),
        migrations.DeleteModel(
            name='Peso',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='veterinario',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='especie',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
        migrations.AddField(
            model_name='ficha',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.especie'),
        ),
    ]
