# Generated by Django 5.0.6 on 2024-06-10 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_ficha_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
