# Generated by Django 5.0.6 on 2024-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_veterinario_ficha_motivo_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
