# Generated by Django 5.0.6 on 2024-05-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_consulta_remove_ficha_veterinario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='motivo_consulta',
            new_name='consulta',
        ),
    ]
