# Generated by Django 5.0.6 on 2024-05-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_rename_consulta_ficha_motivo_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='motivo_consulta',
            new_name='consulta',
        ),
    ]
